package com.faizalempe.covidstatistic.util


// REQUEST CODE
const val REQUEST_GOOGLE_SIGN_IN = 100

// ERROR CODE
const val HTTP_ERROR_BAD_REQUEST = 400
const val HTTP_ERROR_UNAUTHORIZED = 401
const val HTTP_ERROR_FORBIDDEN = 403
const val HTTP_ERROR_NOT_FOUND = 404
const val HTTP_ERROR_METHOD_NOT_ALLOWED = 405
const val HTTP_ERROR_NOT_ACCEPTABLE = 406
const val HTTP_ERROR_PROXY_AUTHENTICATION_REQUIRED = 407
const val HTTP_ERROR_REQUEST_TIMEOUT = 408
const val HTTP_ERROR_CONFLICT = 409
const val HTTP_ERROR_GONE = 410
const val HTTP_ERROR_LENGTH_REQUIRED = 411
const val HTTP_ERROR_PRECONDITION_FAILED = 412
const val HTTP_ERROR_REQUEST_ENTITY_TOO_LARGE = 413
const val HTTP_ERROR_REQUEST_URL_TOO_LONG = 414
const val HTTP_ERROR_UNSUPPORTED_MEDIA_TYPE = 415
const val HTTP_ERROR_REQUEST_RANGE_NOT_SATISFIABLE = 416
const val HTTP_ERROR_EXPECTATION_FAILED = 417
const val HTTP_ERROR_MISDIRECTED_REQUEST = 421
const val HTTP_ERROR_INTERNAL_SERVER = 500
const val HTTP_ERROR_NOT_IMPEMENTED = 501
const val HTTP_ERROR_BAD_GATEWAY = 502
const val HTTP_ERROR_SERVICE_UNAVAILABLE = 503
const val HTTP_ERROR_GATEWAY_TIMEOUT = 504
const val HTTP_ERROR_HTTP_VERSION_NOT_SUPPORTED = 505
const val HTTP_ERROR_VARIANT_ALSO_NEGOTIATES = 506
const val HTTP_ERROR_INSUFFICIENT_STORAGE = 507
const val HTTP_ERROR_LOOP_DETECTED = 508
const val HTTP_ERROR_NOT_EXTENDED = 509
const val HTTP_ERROR_NETWORK_AUTH_REQUIRED = 510
const val UNKNOWN_ERROR = 1000
const val UNKNOWN_HOST_ERROR = 1001